server:
  port: 8848
  servlet:
    context-path: /ayf

alipay:
  appId: 2021004104648092
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCGEgIyuVxJWwaxBOxXm5HYDfGwgfmrAucanqLQOpZk7lrM+xmVYItxtJ4rFIxmGvKKbFAc1VnozEdBPEVUwo2WLije/7qlVYqjyIkI1kzWEuZdz/vELKPe7lqdfKrPenUXVOXJBGPhhf/x+43xnd6Iflahd6fN8LYfLhpkbimc7CLKbJlZ/jeLhtJj+ZQYP9z0POIh6KBkuogFmfWE+9QZJRJADWE/BR92hHq0e6hox6kkXdjwSsNzFOzdvX4T9cTE3y9ZW9n+n4yzacAxOi+qwv+R+HYtEF0o8e24MPztsJJVGhEkDB0B4PYgnWzlm3VpXpDJMP9mOorOsWXZidmLAgMBAAECggEAEydxfvOydpx1mUa9yUpljLt5QyFenQr+H3R4iE1GfUb8W/qnzgqMAYOvcTIvWMsSyantzCDDBppgt7Y3pYNiHQmdNzbL4KEW/I1C3qtXMOJkXRTAwGcsRkZBVeygrqGtJtcvOQfSiT7OsTCiN9m5GEEMeWcR5z8zlcLNbHm8ojl5UyEy9/K2HFd/O3Gm46ohmtvK+aMumhW7yjkWxmya68seklvCl2MUIRu//foKLuMyTxIGOFpZk5zsn7AI1GZlJxaEvkZrrJQS8dUXGMWR27kPiDZsuRrb8ALoyadbCpWx4rkaeuZsl3eiHhTf//wKzNFQkX8UoiPK9Mdmfm2NcQKBgQC6TlU4kGRNzVEsoe1GgvxMj5QNavMpbWCPlmisp/JEqwjqS1MZ6XWCy3DkRul99y/osOhbJjzUazbuqFISieKUqoO2qK8FmUGjLuY6FG3HpUAMX+dg7qg4nq82U0ywbG/6JB2ieOqQ659SS51hei9EMpDvf5qaI9X+oQ7IRXnuKQKBgQC4OU8EA2IGbEb+Zrrl1xMic+C/yVsBTsfqKcZ89m1nEBu1aJ6xOXZ4i3kMvixeUBa/mJtvA7PRSLU4WQAeA4w93rTwH8mDMPWy5Dxo/1VQ7+nwZjVd/Edb4hYSrCrnQqWp7LbXmw6IBBhrixiKXu0kNAnhaKg/AJjZfB+WOmhYkwKBgQCtj9g4r9uh14qt59RighiFQqUMsvwBNhJk8hxl7Lf4XNYbXzz1wNZmmRx8rctMPIH3ZwewErlMsu0j/M8o0iexlADMo+0ZbCMH4OM+bFWxTjOS0618UhmJVduo4oVpPjw7bnXlLHxpsfhk9GiTrP5nrCv10oy22He9lVFuJbtnsQKBgQCDtjWQIPsMrI11he1KNqMvlrmxZTzzimfUO1n2Lhm5/gJRiSMsgnD5bn51ZeJC6+/XvDwk+vitQNaQGtHCo7a45Wln5NImQfLom9W1HBjbbSxM/EZbk+tQ/ivZ3c4u2a+n9d4j+HBDPupWuXQqOgRCRhJqXnEr2jluBRhwSAIikQKBgA998rMRg69dobcT5xMNZGYnh9KZmzr6jUUMk6oJ37FsZfVa/WVOgpeCUSSgJcuYh96HiwvQJhf8ENq7McHgPzelriWUrxg+Sn/Psk8jWQ6e7uiz6e+tWMjkUTSYTsPIzQXrTJACYxeePQi5v1W4UV91+sm+d7mVmx/WrNKpOAsO
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhhICMrlcSVsGsQTsV5uR2A3xsIH5qwLnGp6i0DqWZO5azPsZlWCLcbSeKxSMZhryimxQHNVZ6MxHQTxFVMKNli4o3v+6pVWKo8iJCNZM1hLmXc/7xCyj3u5anXyqz3p1F1TlyQRj4YX/8fuN8Z3eiH5WoXenzfC2Hy4aZG4pnOwiymyZWf43i4bSY/mUGD/c9DziIeigZLqIBZn1hPvUGSUSQA1hPwUfdoR6tHuoaMepJF3Y8ErDcxTs3b1+E/XExN8vWVvZ/p+Ms2nAMTovqsL/kfh2LRBdKPHtuDD87bCSVRoRJAwdAeD2IJ1s5Zt1aV6QyTD/ZjqKzrFl2YnZiwIDAQAB
  gatewayUrl: https://openapi.alipay.com/gateway.do

spring:
  datasource:
    url: jdbc:mysql://60.204.143.76:3306/areyoufull
    username: remote
    password: Remote@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  type-aliases-package: com.ayf.areyoufull.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
