server:
  port: 8848
  servlet:
    context-path: /ayf

spring:
  datasource:
    url: jdbc:mysql://60.204.143.76:3306/areyoufull
    username: remote
    password: Remote@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  type-aliases-package: com.ayf.areyoufull.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
